# Generated by Django 4.2.5 on 2024-08-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Apllication', models.CharField(max_length=500)),
                ('Name', models.CharField(max_length=500)),
                ('age', models.PositiveIntegerField()),
                ('date_of_birth', models.DateField()),
                ('self_email_id', models.EmailField(max_length=255)),
                ('type_of_registration', models.CharField(max_length=500)),
                ('highest_qualification', models.CharField(max_length=500)),
                ('permanent_address_door_no', models.CharField(max_length=100)),
                ('permanent_address_street_name', models.CharField(max_length=500)),
                ('permanent_address_location', models.CharField(max_length=500)),
                ('permanent_address_state', models.CharField(max_length=500)),
                ('permanent_address_pincode', models.CharField(max_length=500)),
                ('mobile_number', models.CharField(max_length=10)),
                ('communication_address_door_no', models.CharField(max_length=100)),
                ('communication_address_street_name', models.CharField(max_length=500)),
                ('communication_address_location', models.CharField(max_length=500)),
                ('communication_address_state', models.CharField(max_length=500)),
                ('communication_address_pincode', models.CharField(max_length=500)),
                ('communication_mobile_number', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('staff_id', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('Department_code', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('confirm_Password', models.CharField(max_length=100)),
            ],
        ),
    ]
