# Generated by Django 4.2.5 on 2024-08-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_no', models.CharField(max_length=200)),
                ('Department', models.CharField(max_length=200)),
                ('research_supervisor', models.CharField(max_length=200)),
                ('Register_Number', models.CharField(max_length=200)),
                ('Area_Research', models.CharField(max_length=200)),
            ],
        ),
    ]
