# Generated by Django 4.2.5 on 2024-08-16 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='aggregate_grade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='class_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='degree',
            field=models.CharField(blank=True, choices=[('B.E', 'Part time'), ('B.tech', 'Full Time')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='discipline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='semester_1',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='semester_2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='semester_3',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='semester_4',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='semester_5',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='semester_6',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='semester_7',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='semester_8',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='university_college',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
