# Generated by Django 4.2.5 on 2024-08-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_personal_details_delete_home'),
    ]

    operations = [
        migrations.DeleteModel(
            name='index',
        ),
        migrations.RemoveField(
            model_name='personal_details',
            name='Apllication',
        ),
        migrations.AddField(
            model_name='personal_details',
            name='Area_Research',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personal_details',
            name='Department',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personal_details',
            name='Register_Number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personal_details',
            name='application_no',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='personal_details',
            name='research_supervisor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='personal_details',
            name='Name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='personal_details',
            name='highest_qualification',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='personal_details',
            name='self_email_id',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personal_details',
            name='type_of_registration',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
