# Generated by Django 4.2.5 on 2024-08-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_delete_index_remove_personal_details_apllication_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_no', models.CharField(blank=True, max_length=500, null=True)),
                ('Name', models.CharField(blank=True, max_length=500, null=True)),
                ('age', models.PositiveIntegerField()),
                ('date_of_birth', models.DateField()),
                ('self_email_id', models.EmailField(blank=True, max_length=255, null=True)),
                ('type_of_registration', models.CharField(blank=True, max_length=500, null=True)),
                ('highest_qualification', models.CharField(blank=True, max_length=500, null=True)),
                ('Department', models.CharField(blank=True, max_length=200, null=True)),
                ('research_supervisor', models.CharField(blank=True, max_length=200, null=True)),
                ('Register_Number', models.CharField(blank=True, max_length=200, null=True)),
                ('Area_Research', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bachelor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=50)),
                ('discipline', models.CharField(max_length=100)),
                ('university_college', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('branch', models.CharField(max_length=100)),
                ('b_class', models.CharField(max_length=50)),
                ('semester_1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('semester_2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('semester_3', models.DecimalField(decimal_places=2, max_digits=5)),
                ('semester_4', models.DecimalField(decimal_places=2, max_digits=5)),
                ('semester_5', models.DecimalField(decimal_places=2, max_digits=5)),
                ('semester_6', models.DecimalField(decimal_places=2, max_digits=5)),
                ('semester_7', models.DecimalField(decimal_places=2, max_digits=5)),
                ('semester_8', models.DecimalField(decimal_places=2, max_digits=5)),
                ('aggregate_grade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DCmembers_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name1', models.CharField(blank=True, max_length=10, null=True)),
                ('Designation_and_Department1', models.CharField(blank=True, max_length=10, null=True)),
                ('College_Organization_Address1', models.CharField(blank=True, max_length=10, null=True)),
                ('Area_of_Research1', models.CharField(blank=True, max_length=10, null=True)),
                ('Name2', models.CharField(blank=True, max_length=10, null=True)),
                ('Designation_and_Department2', models.CharField(blank=True, max_length=10, null=True)),
                ('College_Organization_Address2', models.CharField(blank=True, max_length=10, null=True)),
                ('Area_of_Research2', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mastereducation_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Master_Degree', models.CharField(blank=True, max_length=10, null=True)),
                ('Master_Discipline', models.CharField(blank=True, max_length=100, null=True)),
                ('Master_University', models.CharField(blank=True, max_length=100, null=True)),
                ('Master_Year', models.PositiveIntegerField(blank=True, null=True)),
                ('Master_CGPA', models.FloatField(blank=True, null=True)),
                ('Master_Branch', models.CharField(blank=True, max_length=100, null=True)),
                ('Master_Class', models.CharField(blank=True, max_length=100, null=True)),
                ('Master_Semester_1', models.PositiveIntegerField(blank=True, null=True)),
                ('Master_Semester_2', models.PositiveIntegerField(blank=True, null=True)),
                ('Master_Semester_3', models.PositiveIntegerField(blank=True, null=True)),
                ('Master_Semester_4', models.PositiveIntegerField(blank=True, null=True)),
                ('Master_Aggregate', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='personal_details',
            name='Area_Research',
        ),
        migrations.RemoveField(
            model_name='personal_details',
            name='Department',
        ),
        migrations.RemoveField(
            model_name='personal_details',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='personal_details',
            name='Register_Number',
        ),
        migrations.RemoveField(
            model_name='personal_details',
            name='age',
        ),
        migrations.RemoveField(
            model_name='personal_details',
            name='aggregate_grade',
        ),
        migrations.RemoveField(
            model_name='personal_details',
            name='application_no',
        ),
        migrations.RemoveField(
            model_name='personal_details',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='personal_details',
            name='cgpa',
        ),
        migrations.RemoveField(
            model_name='personal_details',
            name='class_field',
        ),
        migrations.RemoveField(
            model_name='personal_details',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='personal_details',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='personal_details',
            name='discipline',
        ),
        migrations.RemoveField(
            model_name='personal_details',
            name='highest_qualification',
        ),
        migrations.RemoveField(
            model_name='personal_details',
            name='research_supervisor',
        ),
        migrations.RemoveField(
            model_name='personal_details',
            name='self_email_id',
        ),
        migrations.RemoveField(
            model_name='personal_details',
            name='semester_1',
        ),
        migrations.RemoveField(
            model_name='personal_details',
            name='semester_2',
        ),
        migrations.RemoveField(
            model_name='personal_details',
            name='semester_3',
        ),
        migrations.RemoveField(
            model_name='personal_details',
            name='semester_4',
        ),
        migrations.RemoveField(
            model_name='personal_details',
            name='semester_5',
        ),
        migrations.RemoveField(
            model_name='personal_details',
            name='semester_6',
        ),
        migrations.RemoveField(
            model_name='personal_details',
            name='semester_7',
        ),
        migrations.RemoveField(
            model_name='personal_details',
            name='semester_8',
        ),
        migrations.RemoveField(
            model_name='personal_details',
            name='type_of_registration',
        ),
        migrations.RemoveField(
            model_name='personal_details',
            name='university_college',
        ),
        migrations.RemoveField(
            model_name='personal_details',
            name='year',
        ),
    ]
