# Generated by Django 4.2.5 on 2024-08-19 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_bacheloreducationdetails_delete_bachelor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDetails',
            fields=[
                ('application_no', models.CharField(default='your_default_value', max_length=500, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('age', models.PositiveIntegerField()),
                ('date_of_birth', models.DateField()),
                ('self_email_id', models.EmailField(blank=True, max_length=255, null=True)),
                ('type_of_registration', models.CharField(blank=True, max_length=500, null=True)),
                ('highest_qualification', models.CharField(blank=True, max_length=500, null=True)),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
                ('research_supervisor', models.CharField(blank=True, max_length=200, null=True)),
                ('register_number', models.CharField(blank=True, max_length=200, null=True)),
                ('area_research', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DCMember',
            fields=[
                ('application_no', models.CharField(default='your_default_value', max_length=500, primary_key=True, serialize=False)),
                ('name1', models.CharField(blank=True, max_length=100, null=True)),
                ('designation_and_department1', models.CharField(blank=True, max_length=100, null=True)),
                ('college_organization_address1', models.CharField(blank=True, max_length=100, null=True)),
                ('area_of_research1', models.CharField(blank=True, max_length=100, null=True)),
                ('name2', models.CharField(blank=True, max_length=100, null=True)),
                ('designation_and_department2', models.CharField(blank=True, max_length=100, null=True)),
                ('college_organization_address2', models.CharField(blank=True, max_length=100, null=True)),
                ('area_of_research2', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterEducationDetails',
            fields=[
                ('application_no', models.CharField(default='your_default_value', max_length=500, primary_key=True, serialize=False)),
                ('master_degree', models.CharField(blank=True, max_length=10, null=True)),
                ('master_discipline', models.CharField(blank=True, max_length=100, null=True)),
                ('master_university', models.CharField(blank=True, max_length=100, null=True)),
                ('master_year', models.PositiveIntegerField(blank=True, null=True)),
                ('master_cgpa', models.FloatField(blank=True, null=True)),
                ('master_branch', models.CharField(blank=True, max_length=100, null=True)),
                ('master_class', models.CharField(blank=True, max_length=100, null=True)),
                ('master_semester_1', models.PositiveIntegerField(blank=True, null=True)),
                ('master_semester_2', models.PositiveIntegerField(blank=True, null=True)),
                ('master_semester_3', models.PositiveIntegerField(blank=True, null=True)),
                ('master_semester_4', models.PositiveIntegerField(blank=True, null=True)),
                ('master_aggregate', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('application_no', models.CharField(default='your_default_value', max_length=500, primary_key=True, serialize=False)),
                ('permanent_address_door_no', models.CharField(max_length=100)),
                ('permanent_address_street_name', models.CharField(max_length=500)),
                ('permanent_address_location', models.CharField(max_length=500)),
                ('permanent_address_state', models.CharField(max_length=500)),
                ('permanent_address_pincode', models.CharField(max_length=500)),
                ('mobile_number', models.CharField(max_length=10)),
                ('communication_address_door_no', models.CharField(max_length=100)),
                ('communication_address_street_name', models.CharField(max_length=500)),
                ('communication_address_location', models.CharField(max_length=500)),
                ('communication_address_state', models.CharField(max_length=500)),
                ('communication_address_pincode', models.CharField(max_length=500)),
                ('communication_mobile_number', models.CharField(max_length=10)),
                ('father_name', models.CharField(max_length=255)),
                ('father_occupation', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('place_of_birth', models.CharField(max_length=255)),
                ('mother_tongue', models.CharField(max_length=255)),
                ('professional_society_membership', models.CharField(blank=True, max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('state_of_origin', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('marital_status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('appeared_in_gate', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('physically_challenged', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Application_Details',
        ),
        migrations.DeleteModel(
            name='DCmembers_details',
        ),
        migrations.DeleteModel(
            name='Mastereducation_details',
        ),
        migrations.DeleteModel(
            name='Personal_Details',
        ),
        migrations.RemoveField(
            model_name='bacheloreducationdetails',
            name='id',
        ),
        migrations.AddField(
            model_name='bacheloreducationdetails',
            name='application_no',
            field=models.CharField(default='your_default_value', max_length=500, primary_key=True, serialize=False),
        ),
    ]
