# Generated by Django 4.2.5 on 2024-08-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_applicationdetails_dcmember_mastereducationdetails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideDetails',
            fields=[
                ('application_no', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('guide_name', models.CharField(max_length=255)),
                ('guide_designation_and_department', models.CharField(max_length=255)),
                ('guide_recognition_number', models.CharField(max_length=50)),
                ('guide_college_organization_address', models.CharField(max_length=500)),
                ('co_guide_name', models.CharField(blank=True, max_length=255, null=True)),
                ('co_guide_designation_and_department', models.CharField(blank=True, max_length=255, null=True)),
                ('co_guide_recognition_number', models.CharField(blank=True, max_length=50, null=True)),
                ('co_guide_college_organization_address', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bacheloreducationdetails',
            name='bachelor_semester_1',
        ),
        migrations.RemoveField(
            model_name='bacheloreducationdetails',
            name='bachelor_semester_2',
        ),
        migrations.RemoveField(
            model_name='bacheloreducationdetails',
            name='bachelor_semester_3',
        ),
        migrations.RemoveField(
            model_name='bacheloreducationdetails',
            name='bachelor_semester_4',
        ),
        migrations.RemoveField(
            model_name='bacheloreducationdetails',
            name='bachelor_semester_5',
        ),
        migrations.RemoveField(
            model_name='bacheloreducationdetails',
            name='bachelor_semester_6',
        ),
        migrations.RemoveField(
            model_name='bacheloreducationdetails',
            name='bachelor_semester_7',
        ),
        migrations.RemoveField(
            model_name='bacheloreducationdetails',
            name='bachelor_semester_8',
        ),
        migrations.AlterField(
            model_name='bacheloreducationdetails',
            name='application_no',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dcmember',
            name='application_no',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mastereducationdetails',
            name='application_no',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='application_no',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
