# Generated by Django 4.2.5 on 2024-08-19 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_guidedetails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mastereducationdetails',
            name='master_semester_1',
        ),
        migrations.RemoveField(
            model_name='mastereducationdetails',
            name='master_semester_2',
        ),
        migrations.RemoveField(
            model_name='mastereducationdetails',
            name='master_semester_3',
        ),
        migrations.RemoveField(
            model_name='mastereducationdetails',
            name='master_semester_4',
        ),
    ]
