# Generated by Django 5.0.1 on 2024-08-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_remove_mastereducationdetails_master_semester_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name_10th', models.CharField(max_length=255)),
                ('year_of_passing_10th', models.IntegerField()),
                ('std_studied_in_10th', models.CharField(max_length=255)),
                ('medium_of_study_10th', models.CharField(max_length=255)),
                ('school_type_10th', models.CharField(max_length=255)),
                ('total_mark_10th', models.IntegerField()),
                ('school_name_12th', models.CharField(blank=True, max_length=255, null=True)),
                ('year_of_passing_12th', models.IntegerField(blank=True, null=True)),
                ('std_studied_in_12th', models.CharField(blank=True, max_length=255, null=True)),
                ('medium_of_study_12th', models.CharField(blank=True, max_length=255, null=True)),
                ('school_type_12th', models.CharField(blank=True, max_length=255, null=True)),
                ('total_mark_12th', models.IntegerField(blank=True, null=True)),
                ('polytechnic_name', models.CharField(blank=True, max_length=255, null=True)),
                ('year_of_passing_diploma', models.IntegerField(blank=True, null=True)),
                ('studied_in_polytechnic', models.CharField(blank=True, max_length=255, null=True)),
                ('medium_of_study_polytechnic', models.CharField(blank=True, max_length=255, null=True)),
                ('total_mark_polytechnic', models.IntegerField(blank=True, null=True)),
                ('total_percentage_polytechnic', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
