# Generated by Django 5.0.1 on 2024-08-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_schooldetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_experience1', models.CharField(max_length=255)),
                ('name_of_the_organization1', models.CharField(max_length=255)),
                ('start_year1', models.IntegerField()),
                ('to1', models.IntegerField()),
                ('designation1', models.CharField(max_length=255)),
                ('nature_of_work1', models.CharField(max_length=255)),
                ('professional_experience2', models.CharField(blank=True, max_length=255, null=True)),
                ('name_of_the_organization2', models.CharField(blank=True, max_length=255, null=True)),
                ('start_year2', models.IntegerField(blank=True, null=True)),
                ('to2', models.IntegerField(blank=True, null=True)),
                ('designation2', models.CharField(blank=True, max_length=255, null=True)),
                ('nature_of_work2', models.CharField(blank=True, max_length=255, null=True)),
                ('professional_experience3', models.CharField(blank=True, max_length=255, null=True)),
                ('name_of_the_organization3', models.CharField(blank=True, max_length=255, null=True)),
                ('start_year3', models.IntegerField(blank=True, null=True)),
                ('to3', models.IntegerField(blank=True, null=True)),
                ('designation3', models.CharField(blank=True, max_length=255, null=True)),
                ('nature_of_work3', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
