# Generated by Django 5.0.1 on 2024-08-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_experience_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience_details',
            name='id',
        ),
        migrations.RemoveField(
            model_name='schooldetails',
            name='id',
        ),
        migrations.AddField(
            model_name='experience_details',
            name='application_no',
            field=models.CharField(default='your_default_value', max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='application_no',
            field=models.CharField(default='your_default_value', max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bacheloreducationdetails',
            name='application_no',
            field=models.CharField(default='your_default_value', max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dcmember',
            name='application_no',
            field=models.CharField(default='your_default_value', max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='guidedetails',
            name='application_no',
            field=models.CharField(default='your_default_value', max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mastereducationdetails',
            name='application_no',
            field=models.CharField(default='your_default_value', max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='application_no',
            field=models.CharField(default='your_default_value', max_length=500, primary_key=True, serialize=False),
        ),
    ]
