# Generated by Django 4.2.5 on 2024-08-21 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_remove_experience_details_id_remove_schooldetails_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooldetails',
            name='higher_studies',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
