# Generated by Django 4.2.5 on 2024-08-21 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_schooldetails_higher_studies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdetails',
            name='application_no',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
