# Generated by Django 4.2.5 on 2024-08-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0016_alter_bacheloreducationdetails_application_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdetails',
            name='application_no',
            field=models.CharField(default='123', max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='applicationdetails',
            name='register_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bacheloreducationdetails',
            name='application_no',
            field=models.CharField(default='123', max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dcmember',
            name='application_no',
            field=models.CharField(default='123', max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='experience_details',
            name='application_no',
            field=models.CharField(default='123', max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='guidedetails',
            name='application_no',
            field=models.CharField(default='123', max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mastereducationdetails',
            name='application_no',
            field=models.CharField(default='123', max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='application_no',
            field=models.CharField(default='123', max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='schooldetails',
            name='application_no',
            field=models.CharField(default='123', max_length=500, primary_key=True, serialize=False),
        ),
    ]
