# Generated by Django 4.2.5 on 2024-08-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0017_alter_applicationdetails_application_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdetails',
            name='application_no',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
