# Generated by Django 5.0.1 on 2024-09-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0020_alter_applicationdetails_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdetails',
            name='approval',
            field=models.BooleanField(default=False),
        ),
    ]
