# Generated by Django 5.1 on 2024-09-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0021_applicationdetails_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdetails',
            name='register_number',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
