# Generated by Django 5.1 on 2024-09-13 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0022_alter_applicationdetails_register_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('register_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.applicationdetails')),
            ],
        ),
    ]
