# Generated by Django 5.1 on 2024-09-13 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0023_profileimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileImage',
        ),
    ]
